# Generated by Django 5.2.8 on 2025-12-22 06:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CandidateApplication',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=20)),
                ('whatsapp_same', models.BooleanField(blank=True, default=False)),
                ('dob', models.CharField(max_length=20)),
                ('state', models.CharField(max_length=50)),
                ('city', models.CharField(blank=True, max_length=100, null=True)),
                ('pin_code', models.CharField(max_length=6)),
                ('relocation', models.CharField(max_length=3)),
                ('designation', models.CharField(blank=True, max_length=100, null=True)),
                ('highest_qualification', models.TextField()),
                ('experience', models.CharField(max_length=3)),
                ('total_experience', models.CharField(blank=True, max_length=10, null=True)),
                ('current_ctc', models.CharField(blank=True, max_length=20, null=True)),
                ('notice_period', models.CharField(blank=True, max_length=10, null=True)),
                ('expected_monthly_ctc', models.CharField(max_length=20)),
                ('hindi_read', models.CharField(max_length=20)),
                ('hindi_write', models.CharField(max_length=20)),
                ('hindi_speak', models.CharField(max_length=20)),
                ('english_read', models.CharField(max_length=20)),
                ('english_write', models.CharField(max_length=20)),
                ('english_speak', models.CharField(max_length=20)),
                ('facebookLink', models.URLField(blank=True, null=True)),
                ('linkedin', models.URLField(blank=True, null=True)),
                ('short_video_url', models.URLField(blank=True, null=True)),
                ('resume', models.FileField(blank=True, null=True, upload_to='resumes/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=5)),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
            options={
                'verbose_name_plural': 'Countries',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('HR', 'HR+Management'), ('Admin', 'Admin/Tech'), ('Employee', 'Company People'), ('Outsider', 'Outsider')], max_length=20)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='State',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('country', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='states', to='hr.country')),
            ],
        ),
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('state', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cities', to='hr.state')),
            ],
        ),
    ]
