# Generated by Django 5.2.8 on 2026-01-08 08:55

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CandidateApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=20)),
                ('designation', models.CharField(blank=True, max_length=100, null=True)),
                ('experience', models.CharField(max_length=10)),
                ('expected_monthly_ctc', models.CharField(max_length=20)),
                ('resume', models.FileField(blank=True, null=True, upload_to='resumes/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=5)),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
            options={
                'verbose_name_plural': 'Countries',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee_id', models.CharField(blank=True, max_length=20, null=True, unique=True)),
                ('full_name', models.CharField(max_length=100)),
                ('official_email', models.EmailField(blank=True, max_length=254)),
                ('department', models.CharField(max_length=50)),
                ('designation', models.CharField(max_length=50)),
                ('joining_date', models.DateField(blank=True, null=True)),
                ('gender', models.CharField(blank=True, max_length=10)),
                ('personal_email', models.EmailField(blank=True, max_length=254)),
                ('mobile', models.CharField(blank=True, max_length=15)),
                ('employee_category', models.CharField(blank=True, max_length=30, null=True)),
                ('name_of_buddy', models.CharField(blank=True, max_length=100)),
                ('offer_accepted_date', models.DateField(blank=True, null=True)),
                ('planned_joining_date', models.DateField(blank=True, null=True)),
                ('joining_status', models.CharField(blank=True, max_length=20)),
                ('exit_status', models.CharField(default='Active', max_length=20)),
                ('sal_applicable_from', models.DateField(blank=True, null=True)),
                ('basic', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('hra', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('travel_allowance', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('childrens_education_allowance', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('supplementary_allowance', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('employer_pf', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('employer_esi', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('annual_bonus', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('annual_performance_incentive', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('medical_premium', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('medical_reimbursement_annual', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('vehicle_reimbursement_annual', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('driver_reimbursement_annual', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('telephone_reimbursement_annual', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('meals_reimbursement_annual', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('uniform_reimbursement_annual', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('leave_travel_allowance_annual', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('contract_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('contract_period_months', models.PositiveIntegerField(blank=True, null=True)),
                ('next_sal_review_status', models.CharField(blank=True, max_length=50)),
                ('next_sal_review_type', models.CharField(blank=True, max_length=50)),
                ('reason_for_sal_review_not_applicable', models.TextField(blank=True)),
                ('revision_due_date', models.DateField(blank=True, null=True)),
                ('gross_monthly', models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=15)),
                ('monthly_ctc', models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=15)),
                ('gratuity', models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=15)),
                ('annual_ctc', models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=15)),
                ('equivalent_monthly_ctc', models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=15)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='JobDesignation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('jd_link', models.URLField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Contract',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('basic', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('hra', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('travel_allowance', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('childrens_education_allowance', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('supplementary_allowance', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('employer_pf', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('employer_esi', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('annual_bonus', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('annual_performance_incentive', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('medical_premium', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('medical_reimbursement_annual', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('vehicle_reimbursement_annual', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('driver_reimbursement_annual', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('telephone_reimbursement_annual', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('meals_reimbursement_annual', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('uniform_reimbursement_annual', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('leave_travel_allowance_annual', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('gross_monthly', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('monthly_ctc', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('gratuity', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('annual_ctc', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('equivalent_monthly_ctc', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('contract_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('contract_period_months', models.PositiveIntegerField(blank=True, null=True)),
                ('effective_from', models.DateField(default=datetime.date.today)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contracts', to='hr.employee')),
            ],
            options={
                'ordering': ['-effective_from'],
            },
        ),
        migrations.CreateModel(
            name='OTP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('otp', models.CharField(max_length=6)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField()),
                ('used', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Payslip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.CharField(max_length=20)),
                ('file', models.FileField(blank=True, null=True, upload_to='payslips/')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payslips', to='hr.employee')),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('HR', 'HR+Management'), ('Admin', 'Admin/Tech'), ('Employee', 'Company People'), ('Outsider', 'Outsider')], max_length=20)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='State',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='states', to='hr.country')),
            ],
        ),
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('state', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cities', to='hr.state')),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mobile', models.CharField(blank=True, max_length=15, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
