# Generated by Django 5.2.8 on 2026-01-08 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contract',
            name='telephone_allowance',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Telephone Allowance'),
        ),
        migrations.AddField(
            model_name='employee',
            name='telephone_allowance',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15),
        ),
    ]
