# Generated by Django 5.2.8 on 2026-01-03 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0002_alter_employee_employee_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='official_email',
            field=models.EmailField(blank=True, max_length=254),
        ),
    ]
