# Generated by Django 5.2.8 on 2026-01-08 10:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0002_contract_telephone_allowance_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='contract',
            unique_together={('employee', 'effective_from')},
        ),
        migrations.AddField(
            model_name='contract',
            name='breakdown',
            field=models.JSONField(default=dict, help_text='Key = component code, Value = amount (annual unless specified)'),
        ),
        migrations.AddField(
            model_name='contract',
            name='manual_overrides',
            field=models.JSONField(blank=True, default=dict, help_text="e.g., {'TELEPHONE': 2000}"),
        ),
        migrations.AddField(
            model_name='contract',
            name='next_review_status',
            field=models.CharField(default='Due', max_length=50),
        ),
        migrations.AddField(
            model_name='contract',
            name='next_review_type',
            field=models.CharField(default='Annual', max_length=50),
        ),
        migrations.AddField(
            model_name='contract',
            name='reason_not_applicable',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='contract',
            name='revision_due_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='contract',
            name='total_annual_ctc',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Annual CTC entered by HR', max_digits=16),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='contract',
            name='contract_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=16, null=True),
        ),
        migrations.AlterField(
            model_name='contract',
            name='effective_from',
            field=models.DateField(help_text='Salary applicable from this date'),
        ),
        migrations.CreateModel(
            name='CTCComponent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True)),
                ('code', models.CharField(max_length=50, unique=True)),
                ('formula', models.TextField(blank=True, null=True)),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('show_in_documents', models.BooleanField(default=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ctc_components', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'CTC Component',
                'verbose_name_plural': 'CTC Components',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.RemoveField(
            model_name='contract',
            name='annual_bonus',
        ),
        migrations.RemoveField(
            model_name='contract',
            name='annual_ctc',
        ),
        migrations.RemoveField(
            model_name='contract',
            name='annual_performance_incentive',
        ),
        migrations.RemoveField(
            model_name='contract',
            name='basic',
        ),
        migrations.RemoveField(
            model_name='contract',
            name='childrens_education_allowance',
        ),
        migrations.RemoveField(
            model_name='contract',
            name='driver_reimbursement_annual',
        ),
        migrations.RemoveField(
            model_name='contract',
            name='employer_esi',
        ),
        migrations.RemoveField(
            model_name='contract',
            name='employer_pf',
        ),
        migrations.RemoveField(
            model_name='contract',
            name='equivalent_monthly_ctc',
        ),
        migrations.RemoveField(
            model_name='contract',
            name='gratuity',
        ),
        migrations.RemoveField(
            model_name='contract',
            name='gross_monthly',
        ),
        migrations.RemoveField(
            model_name='contract',
            name='hra',
        ),
        migrations.RemoveField(
            model_name='contract',
            name='leave_travel_allowance_annual',
        ),
        migrations.RemoveField(
            model_name='contract',
            name='meals_reimbursement_annual',
        ),
        migrations.RemoveField(
            model_name='contract',
            name='medical_premium',
        ),
        migrations.RemoveField(
            model_name='contract',
            name='medical_reimbursement_annual',
        ),
        migrations.RemoveField(
            model_name='contract',
            name='monthly_ctc',
        ),
        migrations.RemoveField(
            model_name='contract',
            name='supplementary_allowance',
        ),
        migrations.RemoveField(
            model_name='contract',
            name='telephone_allowance',
        ),
        migrations.RemoveField(
            model_name='contract',
            name='telephone_reimbursement_annual',
        ),
        migrations.RemoveField(
            model_name='contract',
            name='travel_allowance',
        ),
        migrations.RemoveField(
            model_name='contract',
            name='uniform_reimbursement_annual',
        ),
        migrations.RemoveField(
            model_name='contract',
            name='vehicle_reimbursement_annual',
        ),
    ]
