# Generated by Django 6.0 on 2025-12-26 18:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0003_employee_alter_candidateapplication_id_alter_city_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payslip',
            name='employee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payslips', to='hr.employee'),
        ),
        migrations.AlterField(
            model_name='payslip',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='payslips/'),
        ),
    ]
