# Generated by Django 5.2.8 on 2026-01-13 07:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0003_alter_contract_unique_together_contract_breakdown_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='supplementary_allowance',
        ),
        migrations.AlterField(
            model_name='contract',
            name='breakdown',
            field=models.JSONField(default=dict, help_text='Key = component code, Value = amount (annual)'),
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, unique=True, verbose_name='Department Name')),
                ('dept_page_link', models.URLField(blank=True, max_length=500, null=True, verbose_name='Department Page Link (BO Internal)')),
                ('dept_head_email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Department Head Email')),
                ('dept_group_email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Department Group Email')),
                ('department_type', models.CharField(choices=[('Delivery', 'Delivery'), ('Support', 'Support')], default='Delivery', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='hr.department', verbose_name='Parent Department')),
            ],
            options={
                'verbose_name': 'Department',
                'verbose_name_plural': 'Departments',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Designation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, verbose_name='Designation')),
                ('role_document_link', models.URLField(blank=True, max_length=500, null=True, verbose_name='Role Document Link')),
                ('jd_link', models.URLField(blank=True, max_length=500, null=True, verbose_name='Job Description (JD) Link')),
                ('remarks', models.TextField(blank=True, null=True)),
                ('role_document_text', models.TextField(blank=True, null=True, verbose_name='Role Document Content (text fallback)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='designations', to='hr.department')),
            ],
            options={
                'verbose_name': 'Designation',
                'verbose_name_plural': 'Designations',
                'ordering': ['department', 'name'],
                'unique_together': {('department', 'name')},
            },
        ),
    ]
