# Generated by Django 5.2.8 on 2026-01-19 09:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0004_remove_employee_supplementary_allowance_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='candidateapplication',
            options={'ordering': ['-created_at'], 'verbose_name': 'Candidate Application', 'verbose_name_plural': 'Candidate Applications'},
        ),
        migrations.AlterModelOptions(
            name='city',
            options={'ordering': ['name']},
        ),
        migrations.AlterModelOptions(
            name='ctccomponent',
            options={'ordering': ['order', 'name']},
        ),
        migrations.AlterModelOptions(
            name='department',
            options={'ordering': ['name']},
        ),
        migrations.AlterModelOptions(
            name='designation',
            options={'ordering': ['department', 'name']},
        ),
        migrations.AlterModelOptions(
            name='state',
            options={'ordering': ['name']},
        ),
        migrations.RemoveField(
            model_name='candidateapplication',
            name='resume',
        ),
        migrations.RemoveField(
            model_name='otp',
            name='used',
        ),
        migrations.AddField(
            model_name='candidateapplication',
            name='city',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='candidate_applications', to='hr.city'),
        ),
        migrations.AddField(
            model_name='candidateapplication',
            name='current_ctc',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='candidateapplication',
            name='dob',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='candidateapplication',
            name='english_read',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='candidateapplication',
            name='english_speak',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='candidateapplication',
            name='english_write',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='candidateapplication',
            name='facebookLink',
            field=models.URLField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='candidateapplication',
            name='highest_qualification',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='candidateapplication',
            name='hindi_read',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='candidateapplication',
            name='hindi_speak',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='candidateapplication',
            name='hindi_write',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='candidateapplication',
            name='linkedin',
            field=models.URLField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='candidateapplication',
            name='notice_period',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='candidateapplication',
            name='pin_code',
            field=models.CharField(blank=True, max_length=6),
        ),
        migrations.AddField(
            model_name='candidateapplication',
            name='relocation',
            field=models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], default='Yes', max_length=3),
        ),
        migrations.AddField(
            model_name='candidateapplication',
            name='short_video_url',
            field=models.URLField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='candidateapplication',
            name='state',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='candidate_applications', to='hr.state'),
        ),
        migrations.AddField(
            model_name='candidateapplication',
            name='total_experience',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='candidateapplication',
            name='updated_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='candidateapplication',
            name='whatsapp_same',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='candidateapplication',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='candidateapplication',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name='candidateapplication',
            name='expected_monthly_ctc',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='candidateapplication',
            name='experience',
            field=models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], default='No', max_length=3),
        ),
        migrations.AlterField(
            model_name='candidateapplication',
            name='full_name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='contract',
            name='breakdown',
            field=models.JSONField(default=dict),
        ),
        migrations.AlterField(
            model_name='contract',
            name='effective_from',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='contract',
            name='manual_overrides',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name='contract',
            name='total_annual_ctc',
            field=models.DecimalField(decimal_places=2, max_digits=16),
        ),
        migrations.AlterField(
            model_name='department',
            name='dept_group_email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='department',
            name='dept_head_email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='department',
            name='dept_page_link',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='department',
            name='name',
            field=models.CharField(max_length=120, unique=True),
        ),
        migrations.AlterField(
            model_name='department',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='hr.department'),
        ),
        migrations.AlterField(
            model_name='designation',
            name='jd_link',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='designation',
            name='name',
            field=models.CharField(max_length=120),
        ),
        migrations.AlterField(
            model_name='designation',
            name='role_document_link',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='designation',
            name='role_document_text',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='employee',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AlterUniqueTogether(
            name='city',
            unique_together={('name', 'state')},
        ),
        migrations.AlterUniqueTogether(
            name='state',
            unique_together={('name', 'country')},
        ),
    ]
