# Generated by Django 5.2.8 on 2026-01-02 05:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0005_employee_photo_alter_candidateapplication_id_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contract',
            options={'ordering': ['-start_date']},
        ),
        migrations.AlterModelOptions(
            name='employee',
            options={'ordering': ['full_name']},
        ),
        migrations.AddField(
            model_name='contract',
            name='contract_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True),
        ),
        migrations.AddField(
            model_name='contract',
            name='contract_period_months',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='candidateapplication',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='city',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='contract',
            name='contract_type',
            field=models.CharField(choices=[('Full-time', 'Full-time'), ('Part-time', 'Part-time'), ('Intern', 'Intern'), ('Temporary Staff', 'Temporary Staff'), ('Contract Based', 'Contract Based')], max_length=30),
        ),
        migrations.AlterField(
            model_name='contract',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='contract',
            name='salary',
            field=models.DecimalField(decimal_places=2, max_digits=15),
        ),
        migrations.AlterField(
            model_name='country',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='current_salary',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15),
        ),
        migrations.AlterField(
            model_name='employee',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name='employee',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='jobdesignation',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='payslip',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='state',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.CreateModel(
            name='ContractBreakdown',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('basic_hra', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Basic + HRA')),
                ('telephone_allowance', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Telephone Allowance')),
                ('travel_allowance', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Travel Allowance')),
                ('childrens_education_allowance', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name="Children's Education Allowance")),
                ('supplementary_allowance', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Supplementary Allowance')),
                ('employer_pf', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Employer PF Contribution')),
                ('employer_esi', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Employer ESI Contribution')),
                ('medical_reimbursement_annual', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('vehicle_reimbursement_annual', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('driver_reimbursement_annual', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('telephone_reimbursement_annual', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('meals_reimbursement_annual', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('uniform_reimbursement_annual', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('leave_travel_allowance_annual', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('annual_bonus', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('annual_performance_incentive', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('medical_premium', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('gratuity', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('contract', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='breakdown', to='hr.contract')),
            ],
            options={
                'verbose_name': 'CTC Breakdown',
                'verbose_name_plural': 'CTC Breakdowns',
            },
        ),
    ]
