# Generated by Django 5.2.8 on 2026-01-19 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0005_alter_candidateapplication_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='candidateapplication',
            options={},
        ),
        migrations.AlterField(
            model_name='candidateapplication',
            name='expected_monthly_ctc',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='candidateapplication',
            name='pin_code',
            field=models.CharField(blank=True, max_length=6, null=True),
        ),
        migrations.AlterField(
            model_name='candidateapplication',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AlterField(
            model_name='candidateapplication',
            name='whatsapp_same',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
