# Generated by Django 5.2.8 on 2026-01-19 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0006_alter_candidateapplication_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidateapplication',
            name='status',
            field=models.CharField(choices=[('Applied', 'Applied'), ('Shortlisted', 'Shortlisted'), ('Rejected', 'Rejected'), ('1st', '1st'), ('2nd', '2nd'), ('3rd', '3rd'), ('Final Interview Round', 'Final Interview Round'), ('Selected', 'Selected'), ('Offer Letter Sent', 'Offer Letter Sent'), ('Offer Letter Accepted', 'Offer Letter Accepted'), ('Offer Letter Accepted But Not Joined', 'Offer Letter Accepted But Not Joined'), ('Joined', 'Joined')], default='Applied', max_length=50),
        ),
    ]
