# Generated by Django 5.2.8 on 2026-01-02 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0006_alter_contract_options_alter_employee_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contractbreakdown',
            name='annual_performance_incentive',
        ),
        migrations.RemoveField(
            model_name='contractbreakdown',
            name='basic_hra',
        ),
        migrations.RemoveField(
            model_name='contractbreakdown',
            name='childrens_education_allowance',
        ),
        migrations.RemoveField(
            model_name='contractbreakdown',
            name='driver_reimbursement_annual',
        ),
        migrations.RemoveField(
            model_name='contractbreakdown',
            name='employer_esi',
        ),
        migrations.RemoveField(
            model_name='contractbreakdown',
            name='leave_travel_allowance_annual',
        ),
        migrations.RemoveField(
            model_name='contractbreakdown',
            name='meals_reimbursement_annual',
        ),
        migrations.RemoveField(
            model_name='contractbreakdown',
            name='medical_premium',
        ),
        migrations.RemoveField(
            model_name='contractbreakdown',
            name='medical_reimbursement_annual',
        ),
        migrations.RemoveField(
            model_name='contractbreakdown',
            name='telephone_allowance',
        ),
        migrations.RemoveField(
            model_name='contractbreakdown',
            name='telephone_reimbursement_annual',
        ),
        migrations.RemoveField(
            model_name='contractbreakdown',
            name='uniform_reimbursement_annual',
        ),
        migrations.RemoveField(
            model_name='contractbreakdown',
            name='vehicle_reimbursement_annual',
        ),
        migrations.AddField(
            model_name='contractbreakdown',
            name='basic_salary',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Basic Salary'),
        ),
        migrations.AddField(
            model_name='contractbreakdown',
            name='employer_esic',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Employer ESIC Contribution'),
        ),
        migrations.AddField(
            model_name='contractbreakdown',
            name='gross_monthly',
            field=models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=15),
        ),
        migrations.AddField(
            model_name='contractbreakdown',
            name='hra',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='HRA (40% of Basic if applicable)'),
        ),
        migrations.AddField(
            model_name='contractbreakdown',
            name='mediclaim_premium',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Mediclaim Premium (Annual)'),
        ),
        migrations.AddField(
            model_name='contractbreakdown',
            name='monthly_ctc',
            field=models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=15),
        ),
        migrations.AddField(
            model_name='contractbreakdown',
            name='telephonic_allowance',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Telephonic Allowance'),
        ),
        migrations.AlterField(
            model_name='contractbreakdown',
            name='annual_bonus',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Annual Bonus'),
        ),
        migrations.AlterField(
            model_name='contractbreakdown',
            name='gratuity',
            field=models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=12),
        ),
    ]
