# Generated by Django 6.0 on 2026-01-21 04:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0007_candidateapplication_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='HiringRequisition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ser', models.CharField(blank=True, max_length=20, null=True, unique=True)),
                ('request_date', models.DateField(auto_now_add=True)),
                ('requisitioner_name', models.CharField(max_length=255)),
                ('requisitioner_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('hiring_dept', models.CharField(max_length=255)),
                ('hiring_dept_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('designation_status', models.CharField(max_length=50)),
                ('hiring_designation', models.CharField(blank=True, max_length=255, null=True)),
                ('new_designation', models.CharField(blank=True, max_length=255, null=True)),
                ('role_link', models.URLField(blank=True, null=True)),
                ('jd_link', models.URLField(blank=True, null=True)),
                ('select_joining_days', models.CharField(max_length=50)),
                ('plan_start_sharing_cvs', models.DateField(blank=True, null=True)),
                ('planned_interviews_started', models.DateField(blank=True, null=True)),
                ('planned_offer_accepted', models.DateField(blank=True, null=True)),
                ('planned_joined', models.DateField(blank=True, null=True)),
                ('special_instructions', models.TextField(blank=True, null=True)),
                ('hiring_status', models.CharField(blank=True, max_length=100, null=True)),
                ('employees_in_cc', models.JSONField(blank=True, default=list)),
                ('role_n_jd_exist', models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], default='Yes', max_length=3)),
                ('role_n_jd_read', models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], default='Yes', max_length=3)),
                ('role_n_jd_good', models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], default='Yes', max_length=3)),
                ('days_well_thought', models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], default='Yes', max_length=3)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Hiring Requisition',
                'verbose_name_plural': 'Hiring Requisitions',
                'ordering': ['-created_at'],
            },
        ),
    ]
