# Generated by Django 5.2.8 on 2026-01-02 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0007_remove_contractbreakdown_annual_performance_incentive_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SalaryStructure',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Name')),
                ('gender', models.CharField(blank=True, choices=[('Male', 'Male'), ('Female', 'Female'), ('Other', 'Other')], max_length=10)),
                ('personal_email', models.EmailField(blank=True, max_length=254, verbose_name='Personal Email')),
                ('mobile', models.CharField(blank=True, max_length=15)),
                ('official_email', models.EmailField(max_length=254, verbose_name='Official Email')),
                ('dept', models.CharField(max_length=50, verbose_name='Dept')),
                ('designation', models.CharField(max_length=50, verbose_name='Designation')),
                ('employee_category', models.CharField(choices=[('Full-time', 'Full-time'), ('Part-time', 'Part-time'), ('Intern', 'Intern'), ('Temporary Staff', 'Temporary Staff'), ('Contract Based', 'Contract Based')], max_length=30, verbose_name='Employee Category')),
                ('name_of_buddy', models.CharField(blank=True, max_length=100, verbose_name='Name of Buddy')),
                ('offer_accepted_date', models.DateField(blank=True, null=True)),
                ('planned_joining_date', models.DateField(blank=True, null=True)),
                ('joining_status', models.CharField(blank=True, max_length=20)),
                ('exit_status', models.CharField(blank=True, choices=[('Active', 'Active'), ('Exited', 'Exited')], default='Active', max_length=20)),
                ('joined_date', models.DateField(verbose_name='Joined Date')),
                ('sal_applicable_from', models.DateField(verbose_name='Sal Applicable From')),
                ('basic', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='Basic')),
                ('hra', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='HRA')),
                ('travel_allowance', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='Travel Allowance')),
                ('childrens_education_allowance', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name="Children's Education Allowance")),
                ('supplementary_allowance', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='Supplementary Allowance')),
                ('employer_pf', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='Employer PF')),
                ('employer_esi', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='Employer ESI')),
                ('annual_bonus', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='Annual Bonus')),
                ('annual_performance_incentive', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='Annual Performance Incentive')),
                ('medical_premium', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='Medical Premium')),
                ('medical_reimbursement_annual', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('vehicle_reimbursement_annual', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('driver_reimbursement_annual', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('telephone_reimbursement_annual', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('meals_reimbursement_annual', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('uniform_reimbursement_annual', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('leave_travel_allowance_annual', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('contract_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True, verbose_name='Contract Amount')),
                ('contract_period_months', models.PositiveIntegerField(blank=True, null=True, verbose_name='Contract Period (months)')),
                ('next_sal_review_status', models.CharField(blank=True, max_length=50, verbose_name='Next Sal Review Status')),
                ('next_sal_review_type', models.CharField(blank=True, max_length=50, verbose_name='Next Sal Review Type')),
                ('reason_for_sal_review_not_applicable', models.TextField(blank=True, verbose_name='Reason for Sal Review Not Applicable')),
                ('revision_due_date', models.DateField(blank=True, null=True, verbose_name='Revision Due Date')),
                ('annual_ctc', models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=15, verbose_name='Annual CTC')),
                ('gross_monthly', models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=15)),
                ('monthly_ctc', models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=15)),
                ('gratuity', models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=15)),
                ('equivalent_monthly_ctc', models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=15)),
            ],
            options={
                'verbose_name': 'Employee Salary Structure',
                'verbose_name_plural': 'Employee Salary Structures',
            },
        ),
    ]
