# Generated by Django 6.0 on 2026-01-21 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0008_hiringrequisition'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hiringrequisition',
            name='designation_status',
        ),
        migrations.RemoveField(
            model_name='hiringrequisition',
            name='hiring_designation',
        ),
        migrations.RemoveField(
            model_name='hiringrequisition',
            name='new_designation',
        ),
        migrations.AddField(
            model_name='hiringrequisition',
            name='dept_group_email',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='Dept Group Email'),
        ),
        migrations.AddField(
            model_name='hiringrequisition',
            name='designation',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Final Designation'),
        ),
        migrations.AddField(
            model_name='hiringrequisition',
            name='designation_existing',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Existing Designation'),
        ),
        migrations.AddField(
            model_name='hiringrequisition',
            name='designation_new',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='New Designation Name'),
        ),
        migrations.AddField(
            model_name='hiringrequisition',
            name='designation_type',
            field=models.CharField(choices=[('existing', 'Existing'), ('new', 'New')], default='existing', max_length=10, verbose_name='Designation Type'),
        ),
        migrations.AlterField(
            model_name='hiringrequisition',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Created At'),
        ),
        migrations.AlterField(
            model_name='hiringrequisition',
            name='days_well_thought',
            field=models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], default='Yes', max_length=3, verbose_name='Days Well Thought?'),
        ),
        migrations.AlterField(
            model_name='hiringrequisition',
            name='employees_in_cc',
            field=models.JSONField(blank=True, default=list, verbose_name='Employees in CC (emails)'),
        ),
        migrations.AlterField(
            model_name='hiringrequisition',
            name='hiring_dept',
            field=models.CharField(max_length=255, verbose_name='Hiring Department'),
        ),
        migrations.AlterField(
            model_name='hiringrequisition',
            name='hiring_dept_email',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='Dept Head Email'),
        ),
        migrations.AlterField(
            model_name='hiringrequisition',
            name='hiring_status',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Hiring Status'),
        ),
        migrations.AlterField(
            model_name='hiringrequisition',
            name='jd_link',
            field=models.URLField(blank=True, null=True, verbose_name='Link to JD'),
        ),
        migrations.AlterField(
            model_name='hiringrequisition',
            name='plan_start_sharing_cvs',
            field=models.DateField(blank=True, null=True, verbose_name='Plan: Start Sharing CVs'),
        ),
        migrations.AlterField(
            model_name='hiringrequisition',
            name='planned_interviews_started',
            field=models.DateField(blank=True, null=True, verbose_name='Planned: Interviews Started By'),
        ),
        migrations.AlterField(
            model_name='hiringrequisition',
            name='planned_joined',
            field=models.DateField(blank=True, null=True, verbose_name='Planned: Joining By'),
        ),
        migrations.AlterField(
            model_name='hiringrequisition',
            name='planned_offer_accepted',
            field=models.DateField(blank=True, null=True, verbose_name='Planned: Offer Accepted By'),
        ),
        migrations.AlterField(
            model_name='hiringrequisition',
            name='request_date',
            field=models.DateField(auto_now_add=True, verbose_name='Request Date'),
        ),
        migrations.AlterField(
            model_name='hiringrequisition',
            name='requisitioner_email',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='Requisitioner Email'),
        ),
        migrations.AlterField(
            model_name='hiringrequisition',
            name='requisitioner_name',
            field=models.CharField(max_length=255, verbose_name='Requisitioner Name'),
        ),
        migrations.AlterField(
            model_name='hiringrequisition',
            name='role_link',
            field=models.URLField(blank=True, null=True, verbose_name='Link to Role'),
        ),
        migrations.AlterField(
            model_name='hiringrequisition',
            name='role_n_jd_exist',
            field=models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], default='Yes', max_length=3, verbose_name='Role & JD Exist?'),
        ),
        migrations.AlterField(
            model_name='hiringrequisition',
            name='role_n_jd_good',
            field=models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], default='Yes', max_length=3, verbose_name='Role & JD Suitable?'),
        ),
        migrations.AlterField(
            model_name='hiringrequisition',
            name='role_n_jd_read',
            field=models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], default='Yes', max_length=3, verbose_name='Role & JD Read?'),
        ),
        migrations.AlterField(
            model_name='hiringrequisition',
            name='select_joining_days',
            field=models.CharField(max_length=50, verbose_name='Select Joining Days'),
        ),
        migrations.AlterField(
            model_name='hiringrequisition',
            name='ser',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True, verbose_name='Serial No'),
        ),
        migrations.AlterField(
            model_name='hiringrequisition',
            name='special_instructions',
            field=models.TextField(blank=True, null=True, verbose_name='Special Instructions to HR'),
        ),
        migrations.AlterField(
            model_name='hiringrequisition',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Updated At'),
        ),
    ]
