# Generated by Django 5.2.8 on 2026-01-02 11:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0009_alter_employee_options_employee_employee_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contractbreakdown',
            name='contract',
        ),
        migrations.DeleteModel(
            name='SalaryStructure',
        ),
        migrations.AlterModelOptions(
            name='contract',
            options={},
        ),
        migrations.AlterModelOptions(
            name='jobdesignation',
            options={},
        ),
        migrations.RemoveField(
            model_name='candidateapplication',
            name='city',
        ),
        migrations.RemoveField(
            model_name='candidateapplication',
            name='current_ctc',
        ),
        migrations.RemoveField(
            model_name='candidateapplication',
            name='dob',
        ),
        migrations.RemoveField(
            model_name='candidateapplication',
            name='english_read',
        ),
        migrations.RemoveField(
            model_name='candidateapplication',
            name='english_speak',
        ),
        migrations.RemoveField(
            model_name='candidateapplication',
            name='english_write',
        ),
        migrations.RemoveField(
            model_name='candidateapplication',
            name='facebookLink',
        ),
        migrations.RemoveField(
            model_name='candidateapplication',
            name='highest_qualification',
        ),
        migrations.RemoveField(
            model_name='candidateapplication',
            name='hindi_read',
        ),
        migrations.RemoveField(
            model_name='candidateapplication',
            name='hindi_speak',
        ),
        migrations.RemoveField(
            model_name='candidateapplication',
            name='hindi_write',
        ),
        migrations.RemoveField(
            model_name='candidateapplication',
            name='linkedin',
        ),
        migrations.RemoveField(
            model_name='candidateapplication',
            name='notice_period',
        ),
        migrations.RemoveField(
            model_name='candidateapplication',
            name='pin_code',
        ),
        migrations.RemoveField(
            model_name='candidateapplication',
            name='relocation',
        ),
        migrations.RemoveField(
            model_name='candidateapplication',
            name='short_video_url',
        ),
        migrations.RemoveField(
            model_name='candidateapplication',
            name='state',
        ),
        migrations.RemoveField(
            model_name='candidateapplication',
            name='total_experience',
        ),
        migrations.RemoveField(
            model_name='candidateapplication',
            name='whatsapp_same',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='current_salary',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='email',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='photo',
        ),
        migrations.AddField(
            model_name='employee',
            name='annual_bonus',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15),
        ),
        migrations.AddField(
            model_name='employee',
            name='annual_ctc',
            field=models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=15),
        ),
        migrations.AddField(
            model_name='employee',
            name='annual_performance_incentive',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15),
        ),
        migrations.AddField(
            model_name='employee',
            name='basic',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15),
        ),
        migrations.AddField(
            model_name='employee',
            name='childrens_education_allowance',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15),
        ),
        migrations.AddField(
            model_name='employee',
            name='contract_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True),
        ),
        migrations.AddField(
            model_name='employee',
            name='contract_period_months',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='employee',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='employee',
            name='driver_reimbursement_annual',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15),
        ),
        migrations.AddField(
            model_name='employee',
            name='employee_category',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='employee',
            name='employer_esi',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15),
        ),
        migrations.AddField(
            model_name='employee',
            name='employer_pf',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15),
        ),
        migrations.AddField(
            model_name='employee',
            name='equivalent_monthly_ctc',
            field=models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=15),
        ),
        migrations.AddField(
            model_name='employee',
            name='exit_status',
            field=models.CharField(default='Active', max_length=20),
        ),
        migrations.AddField(
            model_name='employee',
            name='gender',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AddField(
            model_name='employee',
            name='gratuity',
            field=models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=15),
        ),
        migrations.AddField(
            model_name='employee',
            name='gross_monthly',
            field=models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=15),
        ),
        migrations.AddField(
            model_name='employee',
            name='hra',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15),
        ),
        migrations.AddField(
            model_name='employee',
            name='joining_status',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='employee',
            name='leave_travel_allowance_annual',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15),
        ),
        migrations.AddField(
            model_name='employee',
            name='meals_reimbursement_annual',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15),
        ),
        migrations.AddField(
            model_name='employee',
            name='medical_premium',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15),
        ),
        migrations.AddField(
            model_name='employee',
            name='medical_reimbursement_annual',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15),
        ),
        migrations.AddField(
            model_name='employee',
            name='mobile',
            field=models.CharField(blank=True, max_length=15),
        ),
        migrations.AddField(
            model_name='employee',
            name='monthly_ctc',
            field=models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=15),
        ),
        migrations.AddField(
            model_name='employee',
            name='name_of_buddy',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='employee',
            name='next_sal_review_status',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='employee',
            name='next_sal_review_type',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='employee',
            name='offer_accepted_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='employee',
            name='official_email',
            field=models.EmailField(default='unknown@example.com', max_length=254, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='employee',
            name='personal_email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name='employee',
            name='planned_joining_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='employee',
            name='reason_for_sal_review_not_applicable',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='employee',
            name='revision_due_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='employee',
            name='sal_applicable_from',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='employee',
            name='supplementary_allowance',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15),
        ),
        migrations.AddField(
            model_name='employee',
            name='telephone_reimbursement_annual',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15),
        ),
        migrations.AddField(
            model_name='employee',
            name='travel_allowance',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15),
        ),
        migrations.AddField(
            model_name='employee',
            name='uniform_reimbursement_annual',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15),
        ),
        migrations.AddField(
            model_name='employee',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='employee',
            name='vehicle_reimbursement_annual',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15),
        ),
        migrations.AlterField(
            model_name='candidateapplication',
            name='experience',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='contract',
            name='contract_period_months',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='contract',
            name='salary',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15),
        ),
        migrations.AlterField(
            model_name='employee',
            name='employee_id',
            field=models.CharField(default='unknown@example.com', max_length=20, unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='jobdesignation',
            name='jd_link',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='state',
            name='country',
            field=models.ForeignKey(default='India', on_delete=django.db.models.deletion.CASCADE, related_name='states', to='hr.country'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='ContractBreakdown',
        ),
    ]
