# Generated by Django 6.0 on 2026-01-21 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0009_remove_hiringrequisition_designation_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hiringrequisition',
            name='employees_in_cc',
            field=models.JSONField(blank=True, default=list, verbose_name='Employees in CC (list of emails)'),
        ),
    ]
