# Generated by Django 6.0 on 2026-01-22 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0010_alter_hiringrequisition_employees_in_cc'),
    ]

    operations = [
        migrations.AlterField(
            model_name='country',
            name='code',
            field=models.CharField(max_length=10),
        ),
    ]
