# Generated by Django 5.2.8 on 2026-01-02 11:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0010_remove_contractbreakdown_contract_and_more'),
    ]

    operations = [
    ]
