# Generated by Django 5.2.8 on 2026-01-03 04:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0011_auto_20260102_1724'),
        ('hr', '0012_fix_state_country_fk'),
    ]

    operations = [
    ]
