module.exports = {
  triggerNewOnboarding:         require("./triggers/triggerNewOnboarding"),
  triggerUpdateOnboarding:      require("./triggers/triggerUpdateOnboarding"),
  triggerWeeklyOnboardingEmail: require("./triggers/triggerWeeklyOnboardingEmail"),
  triggerWeeklyHREmail:         require("./triggers/triggerWeeklyHREmail"),
  triggerCandidateApplication:  require("./triggers/triggerCandidateApplication"),
  triggerNewExit:               require("./triggers/triggerExit").triggerNewExit,
  triggerUpdateExit:            require("./triggers/triggerExit").triggerUpdateExit,
  triggerNewRequisition:        require("./triggers/triggerNewRequisition"),
  triggerUpdateRequisition:     require("./triggers/triggerUpdateRequisition"),
  triggerDailyApplicantSummary: require("./triggers/triggerDailyApplicantSummary"),
  triggerReferralInvite:        require("./triggers/triggerReferralInvite"),
  triggerReferralSubmitted:     require("./triggers/triggerReferralSubmitted"),
  triggerReferralBonus:         require("./triggers/triggerReferralBonus"),
  triggerOutOfOfficeNotice:     require("./triggers/triggerOutOfOffice"),
};